config/routes.rb
Bcahl::Application.routes.draw do
  root "pages#index"
  get "/about" => "pages#about", as: :about
  get "/contact" => "pages#contact", as: :contact
  get "/calendar" => "pages#calendar", as: :calendar

  get "/register" => "users#new", as: :new_user
  post "/users" => "users#create", as: :users
  get "/users/:path" => "users#show", as: :user

  get "/sign-in" => "sessions#new", as: :new_session
  post "/sessions" => "sessions#create", as: :sessions
  delete "/sign-out" => "sessions#destroy", as: :session

  patch "/bulletins/:id" => "bulletins#update", as: :bulletin

  get "/players/new" => "players#new", as: :new_player
  get "/players" => "players#index", as: :players
  post "/players" => "players#create"
  get "/players/:path" => "players#show", as: :player
  get "/players/:path/edit" => "players#edit", as: :edit_player
  patch "/players/:path" => "players#update"
  delete "/players/:path" => "players#destroy"

  get "/teams/new" => "teams#new", as: :new_team
  post "/teams" => "teams#create", as: :teams
  get "/teams/:path" => "teams#show", as: :team
  get "/teams" => "teams#index"
  get "/teams/:path/edit" => "teams#edit", as: :edit_team
  patch "/teams/:path" => "teams#update"
  delete "/teams/:path" => "teams#destroy"

  post "/roster_spots" => "roster_spots#create", as: :roster_spots
  delete "/roster_spots/:id" => "roster_spots#destroy", as: :roster_spot

  get "/leagues/new" => "leagues#new", as: :new_league
  post "/leagues" => "leagues#create", as: :leagues
  get "/leagues" => "leagues#index"
  get "/leagues/:path" => "leagues#show", as: :league
  get "/leagues/:path/edit" => "leagues#edit", as: :edit_league
  patch "/leagues/:path" => "leagues#update"
  delete "/leagues/:path" => "leagues#destroy"

  get "/seasons/new" => "seasons#new", as: :new_season
  post "/seasons" => "seasons#create", as: :seasons
  get "/seasons" => "seasons#index"
  get "/leagues/:league_path/seasons/:season_path" => "seasons#show", as: :season
  get "/leagues/:league_path/seasons/:season_path/edit" => "seasons#edit", as: :edit_season
  patch "/leagues/:league_path/seasons/:season_path" => "seasons#update"
  patch "/leagues/:league_path/seasons/:season_path/activate" => "seasons#activate", as: :activate_season
  patch "/leagues/:league_path/seasons/:season_path/deactivate" => "seasons#deactivate", as: :deactivate_season
  delete "/leagues/:league_path/seasons/:season_path" => "seasons#destroy"

  post "/rosters" => "rosters#create", as: :rosters
  get "/leagues/:league_path/seasons/:season_path/rosters/:roster_path" => "rosters#show", as: :roster
  get "/leagues/:league_path/seasons/:season_path/rosters/:roster_path/edit" => "rosters#edit", as: :edit_roster
  patch "/rosters/:id" => "rosters#update"
  delete "/leagues/:league_path/seasons/:season_path/rosters/:roster_path" => "rosters#destroy"

  get "/leagues/:league_path/seasons/:season_path/games/new" => "games#new", as: :new_game
  post "/games" => "games#create", as: :games
  get "/games/:game_id" => "games#show", as: :game
  get "/games/:game_id/edit" => "games#edit", as: :edit_game
  patch "/games/:game_id" => "games#update"
  get "/games/:game_id/score" => "games#score", as: :score_game
  patch "/games/:game_id/update_score" => "games#update_score", as: :update_score
  patch "/games/:game_id/update_stats" => "games#update_stats", as: :update_stats
  delete "/games/:game_id" => "games#destroy"

  get "/events/new" => "events#new", as: :new_event
  post "/events" => "events#create", as: :events
  get "/events/:event_path" => "events#show", as: :event
  get "/events/:event_path/edit" => "events#edit", as: :edit_event
  patch "/events/:event_path" => "events#update"
  delete "/events/:event_path" => "events#destroy"

  resources :galleries do
    resources :photos, except: [:index, :edit, :show, :new]
  end
end

app/models/season.rb
class Season < ActiveRecord::Base
  belongs_to :league
  has_many :teams, through: :rosters
  has_many :rosters, dependent: :destroy
  has_many :games, dependent: :destroy

  validates :name, uniqueness: { scope: :league_id }

  after_validation :create_url_path, on: [ :create, :update ]

  scope :active, -> { where(active: true) }

  def point_leaders
    rosters.includes(:roster_spots).flat_map(&:roster_spots).
      sort { |a, b| b.points <=> a.points }.take(50)
  end

  def create_url_path
    self.path = name.downcase.gsub(" ", "-").gsub("'", "")
  end

  def name_with_league
    "#{league.name} - #{name}"
  end
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  include SessionsHelper

  before_action :set_season, only: [:show, :edit, :update, :activate, :destroy, :deactivate]
  before_action :set_robots, only: [:new, :edit]

  def new
    if signed_in?
      @season = Season.new
    else
      flash[:notice] = "You must be an administrator to access this page."
      redirect_to root_url
    end

    @title = "New Season"
  end

  def create
    @season = Season.new(season_params)

    if @season.save
      flash[:success] = "New season successfully added."
      redirect_to season_url(@season.league.path, @season.path)
    else
      render 'new'
    end
  end

  def index
    @seasons = Season.active

    @title = "Active Seasons | Beaver County Adult Hockey League"
    @meta_description = "View the active seasons in the Beaver County Adult Hockey League."
  end

  def show
    @title = "#{@season.name_with_league} | Beaver County Adult Hockey League"
    @meta_description = "View the schedule, standings, results, and rosters for #{@season.name_with_league}."
  end

  def edit
    @title = "Edit Season"
  end

  def update
    if @season.update(season_params)
      flash[:success] = "Season successfully updated."
      redirect_to season_url(@season.league.path, @season.path)
    else
      render 'edit'
    end
  end

  def activate
    @season.active = true
    if @season.save
      flash[:success] = "Season successfully activated."
      redirect_to edit_season_url(@season.league.path, @season.path)
    else
      render 'show'
    end
  end

  def deactivate
    @season.active = false
    if @season.save
      flash[:success] = "Season successfully deactivated."
      redirect_to edit_season_url(@season.league.path, @season.path)
    else
      render 'show'
    end
  end

  def destroy
    if @season.destroy
      flash[:success] = "Season successfully deleted."
      redirect_to root_url
    else
      flash[:notice] = "Hm. That didn't work as planned."
      redirect_to edit_season_url(@season.league.path, @season.path)
    end
  end

  private
    def season_params
      params.require(:season).permit(:name, :league_id)
    end

    def set_season
      league_id = League.find_by(path: params[:league_path]).id
      @season = Season.find_by(path: params[:season_path], league_id: league_id)
    end

    def set_robots
      @robots = "noindex"
    end
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/views/seasons/_form.html.erb
<%= form_for @season, url: form_action, method: form_method, class: "main-form-type" do |f| %>
  <div class="form-field">
    <%= f.label :name, "Season Name" %>
    <%= f.text_field :name, placeholder: "Fall 2013", required: true %>
  </div>
  <div class="form-field">
    <%= f.label :league_id, "League" %>
    <%= f.collection_select :league_id, League.all, :id, :name, required: true %>
  </div>
  <div class="form-field">
    <%= f.submit form_button %>
  </div>
<% end %>

app/views/seasons/edit.html.erb
<div class="row">
  <div class="span12">
    <div class="page-header">
      <h1>Manage Season: <%= @season.league.name %> - <%= @season.name %></h1>
      <div class="manage-resource-options">
        <%= link_to "Back to #{@season.league.name}", edit_league_url(@season.league.path), class: "manage-resource-option edit-option" %>
        <%= link_to "View Season", season_url(@season.league.path, @season.path), class: "manage-resource-option view-option" %>
        <% if @season.active %>
          <%= link_to "Deactivate Season", deactivate_season_url(@season.league.path, @season.path), method: :patch, class: "manage-resource-option deactivate-option" %>
        <% else %>
          <%= link_to "Activate Season", activate_season_url(@season.league.path, @season.path), method: :patch, class: "manage-resource-option activate-option" %>
        <% end %>
        <%= link_to "Delete Season", season_url(@season.league.path, @season.path), method: :delete, class: "manage-resource-option delete-option" %>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="span12 content-area">
    <div class="manage-row-header">
      <h2>Manage Schedule</h2>
    </div>
    <table class="ui-container season-schedule team-roster">
      <thead>
        <th>Date</th>
        <th>Time</th>
        <th>Home</th>
        <th>Away</th>
        <th>Edit</th>
        <th>Score</th>
        <th>Remove</th>
      </thead>
      <tbody>
        <% @season.games.each do |game| %>
          <tr>
            <td><%= game.date %></td>
            <td><%= game.time %></td>
            <td><%= game.home_team_name %></td>
            <td><%= game.away_team_name %></td>
            <td><%= link_to "Edit Game", edit_game_url(game.id) %></td>
            <td><%= link_to (game.scored? ? "Update Score" : "Score Game"), score_game_url(game.id) %></td>
            <td><%= link_to "Remove Game", game_url(game.id), method: :delete %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="manage-resource-tools">
      <%= link_to "Add Game to Schedule", new_game_url(@season.league.path, @season.path), class: "manage-resource-tool" %>
    </div>
  </div>
</div>
<div class="row">
  <div class="span12">
    <div class="manage-row-header">
      <h2>Manage Rosters</h2>
    </div>
    <div class="manage-row-options">
      <% @season.rosters.each do |roster| %>
        <a href="<%= edit_roster_url(@season.league.path, @season.path, roster.team.path) %>" class="manage-row-edit manage-row-option">
          <h3><%= roster.team.name %></h3>
        </a>
      <% end %>
    </div>
    <div class="manage-resource-tools">
      <%= form_tag rosters_url do %>
        <%= text_field_tag :team_name, nil, placeholder: "Enter Team Name", data: { autocomplete_source: teams_url } %>
        <%= hidden_field_tag :season_id, @season.id %>
        <%= submit_tag "Add Roster", class: "manage-resource-tool" %>
      <% end %>
    </div>
  </div>
</div>

app/views/seasons/index.html.erb
<div class="row">
  <div class="span12">
    <div class="page-header">
      <h1>Current Seasons</h1>
      <div class="manage-resource-options">

      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="span12 content-area">
    <% @seasons.active.each do |season| %>
      <a class="ui-container season-summary" href="<%= season_url(season.league.path, season.path) %>">
        <h3><%= season.name_with_league %></h3>
        <table class="season-summary-standings">
          <% season.rosters.standings.each do |roster| %>
            <tr>
              <td><%= roster.team_name %></td>
              <td><%= roster.points %></td>
            </tr>
          <% end %>
        </table>
      </a>
    <% end %>
  </div>
</div>

app/views/seasons/new.html.erb
<div class="row">
  <div class="span12">
    <div class="page-header">
      <h1>Add New Season</h1>
    </div>
  </div>
</div>
<div class="row">
  <div class="span12 content-area">
    <%= render 'form', form_action: seasons_url, form_method: "post", form_button: "Create Season" %>
  </div>
</div>

app/views/seasons/show.html.erb
<div class="row">
  <div class="span12">
    <div class="page-header">
      <h1>
        <%= "#{@season.name_with_league}" %>
        <% if current_user %>
          <span class="season-status">
            -<% if @season.active %>
              <span class="season-active">Active</span>
            <% else %>
              <span class="season-inactive">Inactive</span>
            <% end %>
          </span>
        <% end %>
      </h1>
      <div class="manage-resource-options">
        <% if current_user %>
          <%= link_to "Edit Season", edit_season_url(@season.league.path, @season.path), class: "manage-resource-option edit-option" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="span12 content-area">
    <div id="season-tabs">
      <ul>
        <li class="clickable-tab"><a href="#tabs-1">Standings</a></li>
        <li class="clickable-tab"><a href="#tabs-2">Schedule</a></li>
        <li class="clickable-tab"><a href="#tabs-3">Statistics</a></li>
        <li class="clickable-tab"><a href="#tabs-4">Rosters</a></li>
      </ul>
      <div id="tabs-1" class="season-tab">
        <table class="team-roster ui-container">
          <thead>
            <th>Team</th>
            <th>Games Played</th>
            <th>Wins</th>
            <th>Losses</th>
            <th>Ties</th>
            <th>OT</th>
            <th>Points</th>
            <th>GF</th>
            <th>GA</th>
          </thead>
          <tbody>
            <% @season.rosters.standings.each do |roster| %>
              <tr>
                <td><%= link_to roster.team.name, roster_url(roster.season.league.path, roster.season.path, roster.team.path) %></td>
                <td><%= roster.games_played %></td>
                <td><%= roster.wins %></td>
                <td><%= roster.losses %></td>
                <td><%= roster.ties %></td>
                <td><%= roster.ot_losses %></td>
                <td><%= roster.points %></td>
                <td><%= roster.goals_for %></td>
                <td><%= roster.goals_against %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div id="tabs-2" class="season-tab">
        <table class="season-schedule team-roster ui-container">
          <thead>
            <th>Date</th>
            <th>Time</th>
            <th>Home</th>
            <th>Away</th>
            <th>Result</th>
          </thead>
          <tbody>
            <% @season.games.each do |game| %>
              <tr>
                <td><%= game.date %></td>
                <td><%= game.time %></td>
                <td><%= game.home_team_name %></td>
                <td><%= game.away_team_name %></td>
                <td><%= game.print_result %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div id="tabs-3" class="season-tab">
        <table class="season-stats team-roster ui-container">
          <thead>
            <th>Player</th>
            <th>Team</th>
            <th>Goals</th>
            <th>Assists</th>
            <th>Points</th>
            <th>PIM</th>
          </thead>
          <tbody>
            <% @season.point_leaders.each do |pl| %>
              <tr>
                <td><%= pl.player.full_name %></td>
                <td><%= pl.roster.team_name %></td>
                <td><%= pl.goals %></td>
                <td><%= pl.assists %></td>
                <td><%= pl.points %></td>
                <td><%= pl.pim %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div id="tabs-4" class="season-tab">
        <div class="row">
          <% @season.rosters.each do |roster| %>
            <div class="span3">
              <div class="ui-container season-roster">
                <h3><%= roster.team_name %></h3>
                <ul>
                <% roster.players.each do |player| %>
                  <li><%= player.full_name %></li>
                <% end %>
                </ul>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>