config/routes.rb
Bcahl::Application.routes.draw do
  root "pages#index"
  get "/about" => "pages#about", as: :about
  get "/contact" => "pages#contact", as: :contact
  get "/calendar" => "pages#calendar", as: :calendar

  get "/register" => "users#new", as: :new_user
  post "/users" => "users#create", as: :users
  get "/users/:path" => "users#show", as: :user

  get "/sign-in" => "sessions#new", as: :new_session
  post "/sessions" => "sessions#create", as: :sessions
  delete "/sign-out" => "sessions#destroy", as: :session

  patch "/bulletins/:id" => "bulletins#update", as: :bulletin

  get "/players/new" => "players#new", as: :new_player
  get "/players" => "players#index", as: :players
  post "/players" => "players#create"
  get "/players/:path" => "players#show", as: :player
  get "/players/:path/edit" => "players#edit", as: :edit_player
  patch "/players/:path" => "players#update"
  delete "/players/:path" => "players#destroy"

  get "/teams/new" => "teams#new", as: :new_team
  post "/teams" => "teams#create", as: :teams
  get "/teams/:path" => "teams#show", as: :team
  get "/teams" => "teams#index"
  get "/teams/:path/edit" => "teams#edit", as: :edit_team
  patch "/teams/:path" => "teams#update"
  delete "/teams/:path" => "teams#destroy"

  post "/roster_spots" => "roster_spots#create", as: :roster_spots
  delete "/roster_spots/:id" => "roster_spots#destroy", as: :roster_spot

  get "/leagues/new" => "leagues#new", as: :new_league
  post "/leagues" => "leagues#create", as: :leagues
  get "/leagues" => "leagues#index"
  get "/leagues/:path" => "leagues#show", as: :league
  get "/leagues/:path/edit" => "leagues#edit", as: :edit_league
  patch "/leagues/:path" => "leagues#update"
  delete "/leagues/:path" => "leagues#destroy"

  get "/seasons/new" => "seasons#new", as: :new_season
  post "/seasons" => "seasons#create", as: :seasons
  get "/seasons" => "seasons#index"
  get "/leagues/:league_path/seasons/:season_path" => "seasons#show", as: :season
  get "/leagues/:league_path/seasons/:season_path/edit" => "seasons#edit", as: :edit_season
  patch "/leagues/:league_path/seasons/:season_path" => "seasons#update"
  patch "/leagues/:league_path/seasons/:season_path/activate" => "seasons#activate", as: :activate_season
  patch "/leagues/:league_path/seasons/:season_path/deactivate" => "seasons#deactivate", as: :deactivate_season
  delete "/leagues/:league_path/seasons/:season_path" => "seasons#destroy"

  post "/rosters" => "rosters#create", as: :rosters
  get "/leagues/:league_path/seasons/:season_path/rosters/:roster_path" => "rosters#show", as: :roster
  get "/leagues/:league_path/seasons/:season_path/rosters/:roster_path/edit" => "rosters#edit", as: :edit_roster
  patch "/rosters/:id" => "rosters#update"
  delete "/leagues/:league_path/seasons/:season_path/rosters/:roster_path" => "rosters#destroy"

  get "/leagues/:league_path/seasons/:season_path/games/new" => "games#new", as: :new_game
  post "/games" => "games#create", as: :games
  get "/games/:game_id" => "games#show", as: :game
  get "/games/:game_id/edit" => "games#edit", as: :edit_game
  patch "/games/:game_id" => "games#update"
  get "/games/:game_id/score" => "games#score", as: :score_game
  patch "/games/:game_id/update_score" => "games#update_score", as: :update_score
  patch "/games/:game_id/update_stats" => "games#update_stats", as: :update_stats
  delete "/games/:game_id" => "games#destroy"

  get "/events/new" => "events#new", as: :new_event
  post "/events" => "events#create", as: :events
  get "/events/:event_path" => "events#show", as: :event
  get "/events/:event_path/edit" => "events#edit", as: :edit_event
  patch "/events/:event_path" => "events#update"
  delete "/events/:event_path" => "events#destroy"

  resources :galleries do
    resources :photos, except: [:index, :edit, :show, :new]
  end
end

app/models/league.rb
class League < ActiveRecord::Base
  has_many :seasons, dependent: :destroy

  validates :name, uniqueness: true

  after_validation :create_url_path, only: [ :create, :update ]

  def create_url_path
    self.path = name.downcase.gsub(" ", "-").gsub("'", "")
  end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  include SessionsHelper

  before_action :set_league, only: [:show, :edit, :update, :destroy]
  before_action :set_robots, only: [:new, :edit]

  def new
    if signed_in?
      @league = League.new
    else
      flash[:notice] = "You must be an administrator to access this page."
      redirect_to root_url
    end

    @title = "New League"
  end

  def create
    @league = League.new(league_params)

    if @league.save
      flash[:success] = "New league successfully added."
      redirect_to user_url(current_user.path)
    else
      render 'new'
    end
  end

  def index
    @leagues = League.all

    @title = "Our Leagues | BCAHL"
    @meta_description = "The Beaver County Adult Hockey League (BCAHL) offers B, D, and E leagues for local players over the age of 18."
  end

  def show
    @title = "#{@league.name} | BCAHL"
    @meta_description = "Check out the BCAHL's #{@league.name}!"
  end

  def edit
  end

  def update
    if @league.update(league_params)
      flash[:success] = "League successfully updated."
      redirect_to league_url(@league.path)
    else
      render 'edit'
    end
  end

  def destroy
    if @league.destroy
      flash[:success] = "League successfully deleted."
      redirect_to root_url
    else
      flash[:notice] = "Hm. That didn't work as planned."
      redirect_to edit_league_url(@league.path)
    end
  end

  private
    def league_params
      params.require(:league).permit(:name)
    end

    def set_league
      @league = League.find_by_path(params[:path])
    end

    def set_robots
      @robots = "noindex"
    end
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/views/leagues/_form.html.erb
<%= form_for @league, url: form_action, method: form_method, class: "main-form-type" do |f| %>
  <div class="form-field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "A League" %>
  </div>
  <div class="form-field">
    <%= f.submit form_button %>
  </div>
<% end %>

app/views/leagues/edit.html.erb
<div class="row">
  <div class="span12">
    <div class="page-header">
      <h1>Manage League: <%= @league.name %></h1>
      <div class="manage-resource-options">
        <%= link_to "Delete League", league_url(@league.path), method: :delete, class: "manage-resource-option delete-option" %>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="span12 content-area">
    <div class="manage-row-header">
      <h2>Manage Seasons</h2>
    </div>
    <div class="manage-row-options">
      <% @league.seasons.each do |season| %>
        <a href="<%= edit_season_url(@league.path, season.path) %>" class="manage-row-edit manage-row-option">
          <h3><%= season.name %></h3>
        </a>
      <% end %>
    </div>
    <div class="manage-resource-tools">
      <a href="<%= new_season_url %>" class="manage-resource-tool">Add Season</a>
    </div>
  </div>
</div>
<div class="row">
  <div class="span12">
    <div class="manage-row-header">
      <h2>Edit League Details</h2>
    </div>
    <%= render 'form', form_action: league_url(@league.path), form_method: "patch", form_button: "Update League"  %>
  </div>
</div>

app/views/leagues/index.html.erb
<div class="row">
  <div class="span12">
    <div class="page-header">
      <h1>Leagues</h1>
    </div>
  </div>
</div>
<div class="row">
  <div class="span12 content-area">
    <% @leagues.each do |league| %>
      <p>
        <%= link_to league.name, league_url(league.path) %>
      </p>
    <% end %>
  </div>
</div>

app/views/leagues/new.html.erb
<div class="row">
  <div class="span12">
    <div class="page-header">
      <h1>Add New League</h1>
    </div>
  </div>
</div>
<div class="row">
  <div class="span12 content-area">
    <%= render 'form', form_action: leagues_url, form_method: "post", form_button: "Create League" %>
  </div>
</div>

app/views/leagues/show.html.erb
<div class="row">
  <div class="span12">
    <div class="page-header">
      <h1><%= @league.name %></h1>
    </div>
  </div>
</div>
<div class="row">
  <div class="span12 content-area">
    <% @league.seasons.each do |season| %>
      <div class="league-season" id="season-<%= season.id %>">
        <%= link_to season.name, season_url(@league.path, season.path) %>
      </div>
    <% end %>
  </div>
</div>