config/routes.rb
Bcahl::Application.routes.draw do
  root "pages#index"
  get "/about" => "pages#about", as: :about
  get "/contact" => "pages#contact", as: :contact
  get "/calendar" => "pages#calendar", as: :calendar

  get "/register" => "users#new", as: :new_user
  post "/users" => "users#create", as: :users
  get "/users/:path" => "users#show", as: :user

  get "/sign-in" => "sessions#new", as: :new_session
  post "/sessions" => "sessions#create", as: :sessions
  delete "/sign-out" => "sessions#destroy", as: :session

  patch "/bulletins/:id" => "bulletins#update", as: :bulletin

  get "/players/new" => "players#new", as: :new_player
  get "/players" => "players#index", as: :players
  post "/players" => "players#create"
  get "/players/:path" => "players#show", as: :player
  get "/players/:path/edit" => "players#edit", as: :edit_player
  patch "/players/:path" => "players#update"
  delete "/players/:path" => "players#destroy"

  get "/teams/new" => "teams#new", as: :new_team
  post "/teams" => "teams#create", as: :teams
  get "/teams/:path" => "teams#show", as: :team
  get "/teams" => "teams#index"
  get "/teams/:path/edit" => "teams#edit", as: :edit_team
  patch "/teams/:path" => "teams#update"
  delete "/teams/:path" => "teams#destroy"

  post "/roster_spots" => "roster_spots#create", as: :roster_spots
  delete "/roster_spots/:id" => "roster_spots#destroy", as: :roster_spot

  get "/leagues/new" => "leagues#new", as: :new_league
  post "/leagues" => "leagues#create", as: :leagues
  get "/leagues" => "leagues#index"
  get "/leagues/:path" => "leagues#show", as: :league
  get "/leagues/:path/edit" => "leagues#edit", as: :edit_league
  patch "/leagues/:path" => "leagues#update"
  delete "/leagues/:path" => "leagues#destroy"

  get "/seasons/new" => "seasons#new", as: :new_season
  post "/seasons" => "seasons#create", as: :seasons
  get "/seasons" => "seasons#index"
  get "/leagues/:league_path/seasons/:season_path" => "seasons#show", as: :season
  get "/leagues/:league_path/seasons/:season_path/edit" => "seasons#edit", as: :edit_season
  patch "/leagues/:league_path/seasons/:season_path" => "seasons#update"
  patch "/leagues/:league_path/seasons/:season_path/activate" => "seasons#activate", as: :activate_season
  patch "/leagues/:league_path/seasons/:season_path/deactivate" => "seasons#deactivate", as: :deactivate_season
  delete "/leagues/:league_path/seasons/:season_path" => "seasons#destroy"

  post "/rosters" => "rosters#create", as: :rosters
  get "/leagues/:league_path/seasons/:season_path/rosters/:roster_path" => "rosters#show", as: :roster
  get "/leagues/:league_path/seasons/:season_path/rosters/:roster_path/edit" => "rosters#edit", as: :edit_roster
  patch "/rosters/:id" => "rosters#update"
  delete "/leagues/:league_path/seasons/:season_path/rosters/:roster_path" => "rosters#destroy"

  get "/leagues/:league_path/seasons/:season_path/games/new" => "games#new", as: :new_game
  post "/games" => "games#create", as: :games
  get "/games/:game_id" => "games#show", as: :game
  get "/games/:game_id/edit" => "games#edit", as: :edit_game
  patch "/games/:game_id" => "games#update"
  get "/games/:game_id/score" => "games#score", as: :score_game
  patch "/games/:game_id/update_score" => "games#update_score", as: :update_score
  patch "/games/:game_id/update_stats" => "games#update_stats", as: :update_stats
  delete "/games/:game_id" => "games#destroy"

  get "/events/new" => "events#new", as: :new_event
  post "/events" => "events#create", as: :events
  get "/events/:event_path" => "events#show", as: :event
  get "/events/:event_path/edit" => "events#edit", as: :edit_event
  patch "/events/:event_path" => "events#update"
  delete "/events/:event_path" => "events#destroy"

  resources :galleries do
    resources :photos, except: [:index, :edit, :show, :new]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :email, uniqueness: true
  validates :l_name, uniqueness: { scope: :f_name }

  after_validation :create_url_path, only: [ :create, :update ]

  def create_url_path
    self.path = f_name.downcase + l_name.first.downcase
  end

  def full_name
    "#{f_name} #{l_name}".titleize
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper

  before_action :set_robots, only: [:new, :show]
  before_action :authorize_super_admin, only: [:new, :create, :update, :destroy]
  before_action :authorize_admin, only: [:show]

  def new
    @user = User.new

    @title = "Add User"
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = "You've successfully created an account."
      sign_in(@user)
      redirect_to user_url(@user.path)
    else
      render 'new'
    end
  end

  def show
    @user = User.find_by_path(params[:path])
    @bulletin = Bulletin.first
    @leagues = League.all
    @teams = Team.all
    @players = Player.all
    @active_seasons = Season.active
    @events = Event.all
    @galleries = Gallery.all

    @title = "Admin Panel"
  end

  def update
  end

  def destroy
  end

  private
    def user_params
      params.require(:user).permit(:f_name, :l_name, :email, :password, :password_confirmation)
    end

    def set_robots
      @robots = "noindex"
    end

    def authorize_super_admin
      redirect_to root_url if current_user.try(:email) != ENV['SUPER_ADMIN_EMAIL'] && Rails.env.production?
    end

    def authorize_admin
      redirect_to root_url unless current_user.path == params[:path]
    end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/new.html.erb
<div class="row">
  <div class="span12">
    <div class="page-header">
      <h1>Create Account</h1>
    </div>
  </div>
</div>
<div class="row">
  <div class="span12 content-area">
    <%= form_for @user, class: "main-form-type" do |f| %>
      <div class="form-field">
        <%= f.label :f_name, "First Name" %>
        <%= f.text_field :f_name, required: true %>
      </div>
      <div class="form-field">
        <%= f.label :l_name, "Last Name" %>
        <%= f.text_field :l_name, required: true %>
      </div>
      <div class="form-field">
        <%= f.label :email, "Email Address" %>
        <%= f.email_field :email, required: true %>
      </div>
      <div class="form-field">
        <%= f.label :password, "Password" %>
        <%= f.password_field :password, required: true %>
      </div>
      <div class="form-field">
        <%= f.label :password_confirmation, "Confirm Password" %>
        <%= f.password_field :password_confirmation, required: true %>
      </div>
      <div class="form-field">
        <%= f.submit "Create Account" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="span12">
    <div class="page-header">
      <h1>Welcome, <%= @user.full_name %>!</h1>
      <p class="page-header-info">Manage leagues, seasons, games, etc. from this page.</p>
    </div>
  </div>
</div>

<div class="row">
  <div class="span12 manage-row-header">
    <h2>Manage Bulletin</h2>
  </div>
</div>
<div class="row">
  <div class="span12 manage-resource-container">
    <%= form_for @bulletin do |f| %>
      <div class="manage-row-options">
        <%= f.text_field :message, placeholder: "Update home page bulletin...", style: "width: 50%; font-size: 12px;" %>
        <label class="form-inline-checkbox-container">
          <%= f.check_box :active, class: "form-inline-checkbox" %> <span>Active</span>
        </label>
      </div>
      <div class="manage-resource-tools">
        <%= f.submit "Update Bulletin", class: "manage-resource-tool" %>
      </div>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="span12 manage-row-header">
    <h2>Manage Active Seasons</h2>
  </div>
</div>
<div class="row">
  <div class="span12 manage-resource-container">
    <div class="manage-row-options">
      <% @active_seasons.each do |season| %>
        <a href="<%= edit_season_url(season.league.path, season.path) %>" class="manage-row-option manage-row-edit">
          <h3><%= season.name_with_league %></h3>
        </a>
      <% end %>
    </div>
    <div class="manage-resource-tools">
      <a href="<%= new_season_url %>" class="manage-resource-tool">Add Season</a>
    </div>
  </div>
</div>
<div class="row">
  <div class="span12 manage-row-header">
    <h2>Manage Leagues</h2>
  </div>
</div>
<div class="row">
  <div class="span12 manage-resource-container">
    <div class="manage-row-options">
      <% @leagues.each do |league| %>
        <a href="<%= edit_league_url(league.path) %>" class="manage-row-option manage-row-edit">
          <h3><%= league.name %></h3>
        </a>
      <% end %>
    </div>
    <div class="manage-resource-tools">
      <a href="<%= new_league_url %>" class="manage-resource-tool">Add League</a>
    </div>
  </div>
</div>
<div class="row">
  <div class="span12 manage-row-header">
    <h2>Manage Teams</h2>
  </div>
</div>
<div class="row">
  <div class="span12 manage-resource-container">
    <div class="manage-row-options">
      <% @teams.each do |team| %>
        <a href="<%= edit_team_url(team.path) %>" class="manage-row-option manage-row-edit">
          <h3><%= team.name %></h3>
        </a>
      <% end %>
    </div>
    <div class="manage-resource-tools">
      <a href="<%= new_team_url %>" class="manage-resource-tool">Add Team</a>
    </div>
  </div>
</div>
<div class="row">
  <div class="span12 manage-row-header">
    <h2>Manage Players</h2>
  </div>
</div>
<div class="row">
  <div class="span12 manage-resource-container">
    <div class="manage-row-options">
      <% @players.each do |player| %>
        <a href="<%= edit_player_url(player.path) %>" class="manage-row-option manage-row-edit">
          <h3><%= player.full_name %></h3>
        </a>
      <% end %>
    </div>
    <div class="manage-resource-tools">
      <a href="<%= new_player_url %>" class="manage-resource-tool">Add Player</a>
    </div>
  </div>
</div>
<div class="row">
  <div class="span12 manage-row-header">
    <h2>Manage Events</h2>
  </div>
</div>
<div class="row">
  <div class="span12 manage-resource-container">
    <div class="manage-row-options">
      <% @events.each do |event| %>
        <a href="<%= edit_event_url(event.path) %>" class="manage-row-option manage-row-edit">
          <h3><%= event.name_and_date %></h3>
        </a>
      <% end %>
    </div>
    <div class="manage-resource-tools">
      <a href="<%= new_event_url %>" class="manage-resource-tool">Add Event</a>
    </div>
  </div>
</div>
<div class="row">
  <div class="span12 manage-row-header">
    <h2>Manage Galleries</h2>
  </div>
</div>
<div class="row">
  <div class="span12 manage-resource-container">
    <div class="manage-row-options">
      <% @galleries.each do |gallery| %>
        <a href="<%= edit_gallery_url(gallery.id) %>" class="manage-row-option manage-row-edit">
          <h3><%= gallery.name %></h3>
        </a>
      <% end %>
    </div>
    <div class="manage-resource-tools">
      <a href="<%= new_gallery_url %>" class="manage-resource-tool">Add Gallery</a>
    </div>
  </div>
</div>