config/routes.rb
Bcahl::Application.routes.draw do
  root "pages#index"
  get "/about" => "pages#about", as: :about
  get "/contact" => "pages#contact", as: :contact
  get "/calendar" => "pages#calendar", as: :calendar

  get "/register" => "users#new", as: :new_user
  post "/users" => "users#create", as: :users
  get "/users/:path" => "users#show", as: :user

  get "/sign-in" => "sessions#new", as: :new_session
  post "/sessions" => "sessions#create", as: :sessions
  delete "/sign-out" => "sessions#destroy", as: :session

  patch "/bulletins/:id" => "bulletins#update", as: :bulletin

  get "/players/new" => "players#new", as: :new_player
  get "/players" => "players#index", as: :players
  post "/players" => "players#create"
  get "/players/:path" => "players#show", as: :player
  get "/players/:path/edit" => "players#edit", as: :edit_player
  patch "/players/:path" => "players#update"
  delete "/players/:path" => "players#destroy"

  get "/teams/new" => "teams#new", as: :new_team
  post "/teams" => "teams#create", as: :teams
  get "/teams/:path" => "teams#show", as: :team
  get "/teams" => "teams#index"
  get "/teams/:path/edit" => "teams#edit", as: :edit_team
  patch "/teams/:path" => "teams#update"
  delete "/teams/:path" => "teams#destroy"

  post "/roster_spots" => "roster_spots#create", as: :roster_spots
  delete "/roster_spots/:id" => "roster_spots#destroy", as: :roster_spot

  get "/leagues/new" => "leagues#new", as: :new_league
  post "/leagues" => "leagues#create", as: :leagues
  get "/leagues" => "leagues#index"
  get "/leagues/:path" => "leagues#show", as: :league
  get "/leagues/:path/edit" => "leagues#edit", as: :edit_league
  patch "/leagues/:path" => "leagues#update"
  delete "/leagues/:path" => "leagues#destroy"

  get "/seasons/new" => "seasons#new", as: :new_season
  post "/seasons" => "seasons#create", as: :seasons
  get "/seasons" => "seasons#index"
  get "/leagues/:league_path/seasons/:season_path" => "seasons#show", as: :season
  get "/leagues/:league_path/seasons/:season_path/edit" => "seasons#edit", as: :edit_season
  patch "/leagues/:league_path/seasons/:season_path" => "seasons#update"
  patch "/leagues/:league_path/seasons/:season_path/activate" => "seasons#activate", as: :activate_season
  patch "/leagues/:league_path/seasons/:season_path/deactivate" => "seasons#deactivate", as: :deactivate_season
  delete "/leagues/:league_path/seasons/:season_path" => "seasons#destroy"

  post "/rosters" => "rosters#create", as: :rosters
  get "/leagues/:league_path/seasons/:season_path/rosters/:roster_path" => "rosters#show", as: :roster
  get "/leagues/:league_path/seasons/:season_path/rosters/:roster_path/edit" => "rosters#edit", as: :edit_roster
  patch "/rosters/:id" => "rosters#update"
  delete "/leagues/:league_path/seasons/:season_path/rosters/:roster_path" => "rosters#destroy"

  get "/leagues/:league_path/seasons/:season_path/games/new" => "games#new", as: :new_game
  post "/games" => "games#create", as: :games
  get "/games/:game_id" => "games#show", as: :game
  get "/games/:game_id/edit" => "games#edit", as: :edit_game
  patch "/games/:game_id" => "games#update"
  get "/games/:game_id/score" => "games#score", as: :score_game
  patch "/games/:game_id/update_score" => "games#update_score", as: :update_score
  patch "/games/:game_id/update_stats" => "games#update_stats", as: :update_stats
  delete "/games/:game_id" => "games#destroy"

  get "/events/new" => "events#new", as: :new_event
  post "/events" => "events#create", as: :events
  get "/events/:event_path" => "events#show", as: :event
  get "/events/:event_path/edit" => "events#edit", as: :edit_event
  patch "/events/:event_path" => "events#update"
  delete "/events/:event_path" => "events#destroy"

  resources :galleries do
    resources :photos, except: [:index, :edit, :show, :new]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>
  <% if @meta_description %>
    <meta name="description" content="<%= @meta_description %>">
  <% end %>
  <% if @robots %>
    <meta name="robots" content="<%= @robots %>">
  <% end %>
  <% if @canonical %>
    <link rel="canonical" href="<%= @canonical %>">
  <% end %>
  <link href='http://fonts.googleapis.com/css?family=Abel' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
  <link rel="shortcut icon" href="https://s3.amazonaws.com/bcahl/assets/favicon.ico">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <% if Rails.env.production? %>
    <script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-26007828-7']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

    </script>
  <% end %>
</head>
<body>
  <% if signed_in? %>
    <header class="admin-header">
      <div class="container">
        <div class="row">
          <div class="span12">
            <nav class="admin-nav-left">
              <%= link_to "Add Player", new_player_url, class: "manage-resource-tool" %>
              <%= link_to "Add Team", new_team_url, class: "manage-resource-tool" %>
              <%= link_to "Add League", new_league_url, class: "manage-resource-tool" %>
              <%= link_to "Add Season", new_season_url, class: "manage-resource-tool" %>
              <%= link_to "Add Event", new_event_url, class: "manage-resource-tool" %>
              <%= link_to "Add Gallery", new_gallery_url, class: "manage-resource-tool" %>
            </nav>
            <nav class="admin-nav-right">
              <%= link_to "Dashboard", user_url(current_user.path), class: "manage-resource-tool" %>
              <%= link_to "Sign Out", session_url, method: "delete", class: "manage-resource-tool" %>
            </nav>
          </div>
        </div>
      </div>
    </header>
  <% end %>
  <header class="main-header">
    <div class="container">
      <div class="row">
        <div class="span12">
          <a class="main-logo" href="/">Beaver County Adult Hockey League</a>
          <nav class="main-nav">
            <%= link_to "Home", root_url %>
            <%= link_to "Current Seasons", seasons_url %>
            <%= link_to "League Calendar", calendar_url %>
            <%= link_to "Photos", galleries_url %>
            <%= link_to "About", "/about" %>
            <%= link_to "Contact", "/contact" %>
          </nav>
        </div>
      </div>
    </div>
  </header>
  <div class="container">
    <div class="row">
      <div class="span12">
        <% flash.each do |name, msg| %>
          <div class="flash-message flash-message-<%= name %>">
            <p class="flash-message-inner">
              <%= msg %>
              <span class="flash-message-fade">&#x2718;</span>
            </p>
          </div>
        <% end %>
      </div>
    </div>
    <%= yield %>
    <footer class="main-footer">
      <span>Beaver County Adult Hockey League - &copy; <%= Time.now.year %></span>
    </footer>
  </div>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
</body>
</html>